# # # -*- coding: utf-8 -*-
# # """WhatsYourTEAM.ipynb
# #
# # Automatically generated by Colaboratory.
# #
# # Original file is located at
# #     https://colab.research.google.com/drive/1ZKiGnmjHMjDmJ6MKul684exMHIa7As4r
# # """
# #
# import random
# import pandas as pd
# import statistics
# from google.colab import drive
#
# drive.mount('/content/drive')
#
# test = pd.read_csv('/content/drive/MyDrive/2020-2023 중앙대학교/2022 3학년/2학기/비즈니스 인텔리전스/KBL.csv')
#
# # Commented out IPython magic to ensure Python compatibility.
# import matplotlib.pyplot as plt
# # %matplotlib inline
# from sklearn.metrics.pairwise import cosine_similarity
# import operator
#
# # cosine으로 사용자 간 유사도를 계산할 때 favorite 값을 제외시키기 위해 temp를 따로 만들어줌
# temp = test.loc[:, test.columns != 'favorite']
#
# # 유저와 유저 간의 유사도 계산
# user_based_collab = cosine_similarity(temp, temp)
# user_based_collab = pd.DataFrame(user_based_collab, index=temp.index, columns=temp.index)
# user = user_based_collab[9].sort_values(ascending=False).index[1]
# print(test.loc[user, 'favorite'])
#
# print(test)
#
# print(temp)
#
# # 유저와 유저 간의 유사도 계산
# user_based_collab = cosine_similarity(temp, temp)
# user_based_collab = pd.DataFrame(user_based_collab, index=temp.index, columns=temp.index)
#
# print(user_based_collab[9].sort_values(ascending=False))
#
# user = user_based_collab[9].sort_values(ascending=False).index[1]
# print(test.loc[user].sort_values(ascending=False))
#
# print(test.loc[user, 'favorite'])
#
# return test.loc[user, 'favorite']
# def test():
#     return 1

import random
import pandas as pd
import statistics
import matplotlib.pyplot as plt
import operator
from sklearn.metrics.pairwise import cosine_similarity

def test():
    test = pd.read_csv('//Users/kitae/Desktop/WhatsYourTeam-BackEnd/src/main/java/WhatsYourTeam/WhatsYourTeamBackEnd/testDB.csv')
    # # cosine으로 사용자 간 유사도를 계산할 때 favorite 값을 제외시키기 위해 temp를 따로 만들어줌
    temp = test.loc[:, test.columns != 'favorite']
    #
    # # 유저와 유저 간의 유사도 계산
    user_based_collab = cosine_similarity(temp, temp)
    user_based_collab = pd.DataFrame(user_based_collab, index=temp.index, columns=temp.index)
    user = user_based_collab[len(temp)-1].sort_values(ascending=False).index[1]

    return test.loc[user, 'favorite']

if __name__ == "__main__":
    print(test())
